meshery-extensions/meshery-consul

README.md

Signed-off-by: Lee Calcote <leecalcote@gmail.com>

update link to new welcome guide

---

.github/workflows/ci.yml

Resolves Issue #357 from [meshery repo](https://github.com/layer5io/meshery/issues/357)

Resolved the docker CI Workflow section from referenced snippet

---

README.md

Fixing badge links as per: https://github.com/layer5io/meshery-consul/issues/20
#20

Fixed badge links

---

README.md
consul/client.go
consul/consul.go
consul/yaml.go

Signed-off-by: Gunjan Paul <gunjan.mtbpaul@gmail.com>

#8 lint failurs solved

---

.github/workflows/ci.yml
consul/client.go
consul/consul.go
main.go

Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

small cgange

---

README.md

Signed-off-by: ashiscs <ashissingh640@gmail.com>

added CII badge and dynamic slack badge

---

.github/workflows/ci.yml
README.md

fixes #29 
Signed-off-by: ashiscs <ashissingh640@gmail.com>

enabled static and error checking of go code

---

.github/workflows/ci.yml
consul/client.go
consul/consul.go
consul/supported_ops.go
consul/yaml.go

Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

#34 Static and error  check fix

---

.github/workflows/ci.yml
consul/consul.go

Signed-off-by: ashiscs <ashissingh640@gmail.com>

updated ci.yml to pass static and error check

---

consul/config_templates/image-hub.yaml
consul/consul.go
consul/supported_ops.go
go.sum

We might want to test it after getting the custom copy of consul on the cluster. But yes the resources do get deployed.
Addresses issue #58 
@leecalcote, @kushthedude, @nveenjain do check! 
Signed-off-by: kanishkarj <kanishkarj@hotmail.com>

Add Image Hub sample app for Consul

---

README.md

fixes #61 
Signed-off-by: ashiscs <ashissingh640@gmail.com>

Updated the status badge

---

.github/workflows/ci.yml

Signed-off-by: Lidor Ettinger <lidor.ettinger@gmail.com>
This PR fixes #64

Push to Docker Hub only in presence of Release Tag

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>
This PR fixes #70

Added ReleaseDrafter configuration files

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

Signed-off-by: tory-brown <vic3brown@gmail.com>

Updated issue templates

---

.github/config.yml

This is the fix for the [issue that was assigned to me at layer5io/meshery-linkerd](https://github.com/layer5io/meshery-linkerd/issues/86)
Signed-off-by: tonyanant <antonis.ant2011@gmail.com>

welcome bot fix /signoff

---

.github/workflows/ci.yml

Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>
This PR fixes #82

changing on push branches filter to include all branches

---

consul/config_templates/README.md
consul/config_templates/consul-values.yaml
consul/config_templates/consul.yaml

Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>
This PR fixes #1 and #2

Updated Consul to 1.8.2 based on Helm chart 0.24.1

---

consul/config_templates/bookinfo.yaml

[App] Update the Deployment version in bookinfo.yaml

---

consul/config_templates/httpbin-consul.yaml

[App] Update the Deployment version in httpbin-consul.yaml

---

consul/supported_ops.go

Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>
This PR fixes #85 
I think it is helpful if the name reflects whether the configuration is unsecured or secured and production-ready, and what kind of environment it requires or can run on, like local (one node) or multiple nodes.

[Install] Modified the name of the installConsulCommand operation

---

.github/workflows/ci.yml

Signed-off-by: Rodolfo Martínez Vega <rodomar@outlook.com>
This PR creates a Github Action workflow to run e2e tests with BATS
This PR fixes #133

[CI] Implement CI workflow to run e2e tests with BATS

---

README.md

Slack Badge Fixed 
This PR fixes #165 
Ready to merge!

[README] Fixed: Slack Badge

---

.github/workflows/newcomers-alert.yml
.github/workflows/slack.yml
README.md

This pr fixes update Slack.yml and add newcomer-alert workflow
This PR fixes #217 

Update Slack.yml and add newcomer-alert workflow

---

helpers/component_info.json

Signed-off-by: asubedy <frexpe@pm.me>
Updated adapter name in `component_info.json` for uniformity in the naming of components.

updated adapter name in component_info.json

---

Dockerfile

Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
Related to meshery/meshery#4642
Needs check

Bump tags for CVE fix

---

main.go

Signed-off-by: asubedy <frexpe@pm.me>

changed version none to edge

---

consul/error.go

Signed-off-by: asubedy <frexpe@pm.me>

enhanced OAM error description

---

Dockerfile

Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

Fix failing static component registeration

---

.github/workflows/ci.yml

Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

change linter to latest version

---

.github/workflows/ci.yml
consul/oam/error.go
helpers/component_info.json
internal/config/error.go

Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

Add err code utility runner

---

main.go

Remove trait registeration

---

Makefile
build/Makefile.core.mk
build/Makefile.show-help.mk

Signed-off-by: leecalcote <leecalcote@gmail.com>

Normalize Makefile

---

README.md

Signed-off-by: Nishant Mittal <mittalnishant14@outlook.com>
This PR fixes N/A.

docs: fix twitter url in readme

---

consul/oam.go
go.mod
go.sum
templates/oam/workloads/1.10.4/consulmesh.meshery.layer5io.schema.json
templates/oam/workloads/1.10.4/consulmesh_definition.json
templates/oam/workloads/1.11.1/consulmesh.meshery.layer5io.schema.json
templates/oam/workloads/1.11.1/consulmesh_definition.json
templates/oam/workloads/1.11.2/consulmesh.meshery.layer5io.schema.json
templates/oam/workloads/1.11.2/consulmesh_definition.json
templates/oam/workloads/1.11.3/consulmesh.meshery.layer5io.schema.json
templates/oam/workloads/1.11.3/consulmesh_definition.json
templates/oam/workloads/1.11.4/consulmesh.meshery.layer5io.schema.json
templates/oam/workloads/1.11.4/consulmesh_definition.json
templates/oam/workloads/1.12.0/consulmesh.meshery.layer5io.schema.json
templates/oam/workloads/1.12.0/consulmesh_definition.json
templates/oam/workloads/1.12.2/consulmesh.meshery.layer5io.schema.json
templates/oam/workloads/1.12.2/consulmesh_definition.json
templates/oam/workloads/1.12.3/consulmesh.meshery.layer5io.schema.json
templates/oam/workloads/1.12.3/consulmesh_definition.json

Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

Upgrade meshkit/adapter-library and versioning

---

consul/operations.go
go.mod
go.sum

Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>
This PR enables sending complete error details to client;
1. Error Code
2. Cause
3. Remedy
4. Component Type
5. Component Name

Send detailed error response to client

---

Makefile

Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>
`Makefile` includes the adapter choice as `istio`, not `consul`
- [ x  ] Yes, I signed my commits.

Renamed adapter from istio to consul for Docker image tag

---

consul/consul.go
consul/oam.go
consul/operations.go
go.mod
go.sum
main.go

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

Add Event streamer struct

---

.github/workflows/multi-platform.yml
Dockerfile
Makefile

This PR updates:
related to https://github.com/meshery/meshery/issues/6245

[chore] Update Adapter Build files

---

Dockerfile

Signed-off-by: revolyssup <ashishjaitiwari15112000@gmail.com>

Fix failing container

---

Makefile
build/Makefile.core.mk

Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>
This PR relaxes Go 1.19 requirement

Relax Go req

---

.github/workflows/e2etests.yaml

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

Change pod assertions in E2E tests

---

.github/workflows/e2etests.yaml

Signed-off-by: Sekiranda Hamza <sekirandahamza@gmail.com>
Match resource and namespace count in resource assertion job.

Align-namespaces-in-e2e-test. Signed-Off-By: Sekiranda Hamza sekirandahamza@gmail.com

---

build/config.go

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

externalize json

---

main.go

Fix failing adapter

---

.github/workflows/e2etests.yaml

Update e2etests.yaml to reference v2 workflow

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md

feat:updated issue template with figma links

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/ci.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/config.yml
.github/label-commenter-config.yml
.github/workflows/build-and-release.yml
.github/workflows/ci.yml
.github/workflows/components-to-doc.yml
.github/workflows/e2etests.yaml
.github/workflows/label-commenter.yml
.github/workflows/multi-platform.yml
.github/workflows/release-drafter.yml
.github/workflows/update-oam-defs.yml
CONTRIBUTING.md
Makefile
README.md
main.go

chore: move hub repos

---

.github/workflows/build-and-release.yml
.github/workflows/multi-platform.yml

Signed-off-by: Hortison <160366376+hortison@users.noreply.github.com>

chore: update dockerhub-description action to v2
